fix: xhci: fix xhci mainline compile issue in Aarch64
	In mainline xhci driver, uint_32 is used hold pointer, which would
	cause a compilation error in Aarch64.
	To fix this, change uint_32 to uintprt_t, which compiles both in Aarch32
	and Aarch64.

Change-Id: Idaf14e69e65d56203864432db98ceccc555f23a0
Signed-off-by: Jing Hua <jinghua@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/24728
Reviewed-by: Hezi Shahmoon <hezi@marvell.com>
Reviewed-by: Hanna Hawa <hannah@marvell.com>
Tested-by: Hanna Hawa <hannah@marvell.com>