fix: bobk: serdes: fix typo which caused compilation error for customer
Change-Id: I6240d037b8cec33d02e4d48cfe99884d11d29178
Signed-off-by: Margarita Granov <margra@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/22640
Reviewed-by: Omri Itach <omrii@marvell.com>
Tested-by: Star_Automation <star@marvell.com>