fix: bubt: mvebu: fix the compilation error for USB bubt
    when adding support of bubt command for Armada3700, there are
    compilation errores, since USB_STORAGE is supported for Armada3700.
    To fix this, include usb.h and fs.h and add the 5th input param to
    invoke routine fs_read.

    NOTE, bubt from USB has not been tested yet, this patch only fixes
    the compilation error.

Change-Id: I8eae89f073b7e02e06739da245b09eb40903a9c6
Signed-off-by: jinghua <jinghua@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/25453
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>