arm: config: a38x: modify spl image offset
Currently, SPL image overrides u-boot image, casuing compilation error.
This patch updates the SPL image offset (CONFIG_SYS_SPI_U_BOOT_OFFS) to
0x26000, fixing the compilation error.

Change-Id: I3ccf044f81916d1b97d0e0f61ab145a954448fc4
Signed-off-by: Igal Liberman <igall@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/55289
Reviewed-by: Neta Zur Hershkovits <neta@marvell.com>
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
(cherry picked from commit 533fdbbdf515bc954d39e3bcf4a06f3029c68cfd)
Reviewed-on: http://vgitil04.il.marvell.com:8080/55388