fix: ddr3: a38x: fix compilation failure on customer board with DDR4
	When compiling for customer board (any of them) with DDR4
	(with '-m 4' flag) compilation error occurs.
	- SPEED_BIN_DDR_CLEARFOG_BOARD and BUS_WIDTH_CLEARFOG_BOARD defines
	  were only defined for DDR3
	- The fix changes the defines to be defined to the same value when
	  compiling for DDR3/4, since there is no Clear Fog board with DDR4

Change-Id: I96490b3d08a2d8f2d913d00e9413146d40765f2f
Signed-off-by: Bassel Saba <basselsa@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/25330
Tested-by: Star_New_DDR <star-new-ddr@marvell.com>
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/25451
Reviewed-on: http://vgitil04.il.marvell.com:8080/25503
Reviewed-by: Nadav Haklai <nadavh@marvell.com>