fix: ddr4: always build main DDR libraries for DDR4
General:
DDR4 (only) include 2 DDR libraries:
1. ddr[3/4]_training_a38x.lib	: a38x: built by default with each compilation
                                  a39x: using pre-built ddr library.
2. ddr4_training_a38xsub.lib	: pre-compiled and supplied in the release,
				  linked in each compilation

Issue: the 1st library should be compiled for both DDR3 & DDR4.
DDR4 compilation failed since the the 1st library was compiled only for DDR3.

Fix:
1. set the 1st library to be compiled by default, also for DDR4 with A38x.
(A39x is still using pre-built libraries for both)
2. Updates 2nd lib file (DDR4 A38x sub-lib), which is required for each new build of library 1.

Change-Id: Ied3c94954482a8c8c3cce603160b1a8ac3fedb79
Signed-off-by: Omri Itach <omrii@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/24519