fix: gpio: pca953x: fix the backporting errors
- This patch is to fix the compilation errors after backforward porting
  the following PCA953x gpio driver to u-boot-2015.01.
    [1/3] gpio: pca953x: Fix register reading past 8th GPIO
    [2/3] dm: gpio: pca953x: Support PCA953X with 40 GPIOs
    [3/3] dm: gpio: pca953x: introduce driver model support for pca953x
- The PCA953x gpio driver uses dm_i2c_xxx apis, which is not provisioned
  in u-boot-2015.01. Though the current u-boot supports the DM I2C driver,
  neither Armada3700 nor Armada-70x0/80x0's I2C driver support it.
  Thus, the legacy i2c_read/write apis are used for non-DM support.
- The legacy I2C driver also not supports the I2C interface's status.
  So it is assumed that I2C interface has already been initialized
  before probing the PCA953x gpio driver.
- The 'xlate' callbacks of UCLASS GPIO driver are not supported
  in u-boot-2015.01. It was removed from the driver.
- Also, it adaptes a few device apis in the probe function.

Change-Id: I4cab20068409d629fb19329acd726d3f485299be
Signed-off-by: Terry Zhou <bjzhou@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/31348
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>
Reviewed-by: Wilson Ding <dingwei@marvell.com>