A375,ALP: Fixed chip define for bin_hdr.
        Fixed config_marvell.h to use different defines for A375 and ALP.
        Added appropriate cases in all bin_hdr makefiles.
        Fixed compilation errors for A375 caused by use of rigth .h files.
        Fixed mc static values for A375 board.

Change-Id: I369862dcb076ab46d0cf0046525a2ecb3af2e40a
Reviewed-on: http://vgitil04.il.marvell.com:8080/2292
Reviewed-by: Omri Itach <omrii@marvell.com>
Reviewed-by: Star_Automation <star@marvell.com>
Reviewed-by: Igor Patrik <igorp@marvell.com>
Tested-by: Igor Patrik <igorp@marvell.com>