fix: bin_hdr: remove HOSTCFLAGS from setparams make command
	The HOSTCFLAGS keep the upper layer $(INCLUDE) value
	The wrong HOSTCFLAGS cause to compilation error to the vxWorks Boot Loader

Change-Id: I476961227be5edb218b32cf5d3dd00204380ec41
Signed-off-by: Neta Zur <neta@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/4304
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Eli Nidam <elini@marvell.com>
Reviewed-by: Nadav Haklai <nadavh@marvell.com>