fix: usb: a3700: fix usb2 compilation error
- When ehci driver is enabled, the uboot build failed with some
  compilation issue. It is caused by missing the gpio head file
  required by the new api - usb_vbus_gpio_toggle().
- This patch includes gpio header file in ehci driver.

Change-Id: I5a36c46bf3c468b5be4ef3ab49bc424ecb07cad8
Signed-off-by: Ken Ma <make@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/31662
Reviewed-by: Wilson Ding <dingwei@marvell.com>
Tested-by: Wilson Ding <dingwei@marvell.com>