ehci: mvebu: add option to bypass address decode configuratin for USB2
For Marvell SoCs like A38x, AXP and A37x, USB2 controller needs address
decode table configurations, which is in file ehci-marvell.c, but for some
other SoC it is not needed, like A3700, and need to be disabled, otherwise
there will be compilation error since there is no the same routines as A38x,
AXP and A37x to do the addr decode.
- add USB_EHCI_MARVELL_BYPASS_BRG_ADDR_DEC to Kconfig as default value n,
  so it would break any SoCs that have already had EHCI support.
- put all the USB2 address decode configuration code in ehci-marvell.c under
  it.

Change-Id: I96e88fa6c49308be1a74aac677d93d434df1e9a5
Signed-off-by: jinghua <jinghua@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/28345
Reviewed-by: Wilson Ding <dingwei@marvell.com>
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>