fix: Examples Makefile causes compilation error
The Makefile in u-boot examples folder breaks compilation
of Yocto due to missing libgcc location when USE_PRIVATE_LIBGCC
is defined.
This patch fixes this issue by checking the value of
USE_PRIVATE_LIBGCC and acting accordingly.

Change-Id: Ib40b725feec9b3383f5a91d9500ef76999a31b80
Signed-off-by: Konstantin Porotchkin <kostap@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/34110
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Neta Zur Hershkovits <neta@marvell.com>