Revert "fix: compilation error when enable FDT in config"
- This reverts commit 5e9f0eed206425afed5bc0ea365afa5d8cd4bab5.
- It can be reverted since the issue was fixed in patch:
  63db7e510cda380359a7052eb01947307199539b

Change-Id: I4d3a016a9253685b14760adcb0f3d4c4a0a825b7
Reviewed-on: http://vgitil04.il.marvell.com:8080/27614
Reviewed-by: Haim Boot <hayim@marvell.com>
Tested-by: Haim Boot <hayim@marvell.com>