fix: uart: armada3700: add BAUDRATE define in mvebu-common.h for armada3700
	in mvebu-common.h, BAUDRATE used to be defined when CONFIG_SYS_NS16550
	is defined.
	But for Armada3700, MVEBU_UART_ARLP uart driver is used, so
	BAUDRATE is missing.

	when compile Palladium image, there is another BAUDRATE in armadalp.h,
	which is specified for Palladium, so there is no compilation error.

Change-Id: I1d12112050a59f8d28ad74db597e769bc0f5997d
Signed-off-by: jinghua <jinghua@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/24994
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>